import { fromRawRenderConfig } from '../types/config';

export const renderConfig = fromRawRenderConfig({
  pageHeight: 2828.4,
  lineWidth: 1500,
  lineGap: 30,
  smuflSize: 36,
  glyphHeight: 30,
  glyphWidth_glyphHeight: 2 / 3,
  repeater4Height_glyphHeight: 1 / 8,
  repeater4Width_glyphWidth: 9 / 10,
  transposeDotRadius_glyphHeight: 1 / 8,
  transposeDotGap_glyphHeight: 1 / 8,
  dotRadius_glyphHeight: 1 / 8,
  dotGap_glyphHeight: 1 / 8,
  beamHeight_glyphHeight: 1 / 10,
  beamGap_glyphHeight: 1 / 8,
  accidentalYOffset_glyphHeight: -1 / 5,
  symbolXGap_glyphWidth: 1 / 8,
  symbolYGap_glyphHeight: 1 / 4,
  barLineLength_glyphHeight: 3 / 2,
  barLineWidth_glyphWidth: 1 / 10,
  barLineLeftPadding_glyphWidth: 3 / 2,
  barLineRightPadding_glyphWidth: 3 / 2,
  thickBarLineWidth_barLineWidth: 5 / 2,
  thickBarLineGap_barLineWidth: 3 / 2,
  slurHeight_glyphHeight: 1 / 2,
  slurPaddingX_glyphWidth: 1 / 8,
  slurPaddingBottom_glyphHeight: 1 / 8,
  lyricSize_glyphHeight: 1,
  lyricGap_lineGap: 1 / 4,
  chordGap_glyphHeight: 1 / 3,
  chordYscale: 2 / 3,
  timeSignatureYScale: 3 / 4,
  timeSignatureLeftPadding_glyphWidth: 3 / 2,
  timeSignatureRightPadding_glyphWidth: 3 / 2,
  initialTimeSignature: [4, 4],
  numFontFilename: 'LathaBold.ttf',
  smuflFontFilename: 'Leland.otf',
});
