import { fromRawRenderConfig } from '../types/config';

export const renderConfig = fromRawRenderConfig({
  pageHeight: 2828.4,
  lineWidth: 1500,
  lineGap: 30,
  glyphHeight_lineWidth: 1 / 50,
  glyphWidth_glyphHeight: 3 / 4,
  repeater4Height_glyphHeight: 1 / 8,
  repeater4Width_glyphWidth: 9 / 10,
  transposeDotRadius_glyphHeight: 1 / 8,
  transposeDotGap_glyphHeight: 1 / 8,
  dotRadius_glyphHeight: 1 / 8,
  dotGap_glyphHeight: 1 / 8,
  beamHeight_glyphHeight: 1 / 10,
  beamGap_glyphHeight: 1 / 8,
  accidentalHeight_glyphHeight: 7 / 10,
  accidentalWidth_accidentalHeight: 1 / 2,
  barLineLength_glyphHeight: 3 / 2,
  barLineWidth_glyphWidth: 1 / 10,
  barLineLeftPadding_glyphWidth: 3 / 2,
  barLineRightPadding_glyphWidth: 3 / 2,
  thickBarLineWidth_barLineWidth: 3,
  thickBarLineGap_barLineWidth: 2,
  slurHeight_glyphHeight: 1 / 2,
  slurPaddingX_glyphWidth: 1 / 8,
  slurPaddingBottom_glyphHeight: 1 / 8,
  lyricSize_glyphHeight: 1,
  lyricGap_lineGap: 1 / 4,
  initialTimeSignature: [4, 4],
});
